apiVersion: v1
kind: Service
metadata:
  name: tghnjk  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "tghnjk"
    port: 8080
  selector:
    app: tghnjk
